version:                 "3"
services:
  nodedatabase:
    build:               ./postgres-docker
    container_name:      postgres-node
    restart:             unless-stopped
    volumes:
      - ~/stellar-test/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     stellar
      POSTGRES_DB:       coredb
      POSTGRES_PASSWORD: password
    networks:
      - default

  stellarcore:
    image:               sgehrman/stellar-node
    container_name:      stellar-node
    volumes:
      - ~/stellar-test:/opt/stellar
    restart:             unless-stopped
    depends_on:
      - nodedatabase
    environment:
      POSTGRES_PASSWORD: password
      TESTNET:           1
      CORE_DB_DSN:       "postgresql://dbname=coredb host=nodedatabase user=stellar password=password sslmode=disable"
      HORIZON_DB_DSN:    "postgres://stellar:password@nodedatabase/horizondb?sslmode=disable"
    ports:
      - "8000:8000"
    networks:
      - default
