version: "3"
services:
  database:
    image: postgres
    container_name: postgres-node
    restart: unless-stopped
    volumes:
      - ~/stellar-test/postgres-horizon:/var/lib/postgresql/data
    networks:
      - default

  stellarcore:
    image: sgehrman/stellar-node
    container_name: stellar-node
    volumes:
      - ~/stellar-test:/opt/stellar
    restart: unless-stopped
    depends_on:
      - database
    environment:
      TESTNET: 1
      HORIZON_DB_DSN: "postgres://stellar@database/horizondb?sslmode=disable"
      CORE_DB_DSN: "postgres://stellar@database/coredb?sslmode=disable"
    ports:
      - "8000:8000"
    networks:
      - default
