version: "3"
services:
  stellar_core:
      image: sgehrman/stellar-node
      command: --testnet
      container_name: stellar-node
      volumes:
        - ~/stellar-test:/opt/stellar
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: password
      ports:
        - "8000:8000"
